# File generated by Flopy version 3.9.2 on 05/22/2025 at 16:05:25.
BEGIN attributes
  NAMES  rch_1
  METHODS  stepwise
END attributes

BEGIN timeseries
       0.00000000       0.00150000
       1.00000000       0.00100000
      11.00000000       0.00150000
      21.00000000       0.00250000
      31.00000000       0.00150000
END timeseries

